version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 80:80 # Troque a porta caso seja necess√°rio
    volumes:
      - .:/var/www/html
    links:
      - databasebravi
  databasebravi:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bravi
      MYSQL_USER: root
      MYSQL_PASSWORD: bravi123
      MYSQL_ROOT_PASSWORD: bravi123
  phpqa:
    image: jakzal/phpqa:php7.1-alpine
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
     - "8080:80"
    links:
     - "databasebravi:db"